# Generated by Django 4.0.6 on 2022-08-08 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelanco', '0003_proposals_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progess'), ('completed', 'Completed'), ('revoked_by_freelancer', 'Revoked'), ('revoked_by_customer', 'Revoked')], default='in_progress', max_length=50)),
                ('freelancer_completed', models.BooleanField(default=False)),
                ('company_completed', models.BooleanField(default=False)),
                ('eth_contract_address', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanco.company')),
                ('freelancer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanco.freelancer')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanco.jobs')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freelanco.proposals')),
            ],
        ),
    ]
