# Generated by Django 4.0.6 on 2022-08-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanco', '0004_contracts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('contract_running', 'In Progress'), ('closed', 'Closed')], default='open', max_length=50),
        ),
    ]
