# Generated by Django 4.0.6 on 2022-08-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanco', '0009_alter_proposals_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progess'), ('deposited', 'Deposited'), ('completed', 'Completed'), ('revoked_by_freelancer', 'Revoked'), ('revoked_by_customer', 'Revoked')], default='in_progress', max_length=50),
        ),
    ]
