# Generated by Django 4.0.6 on 2022-08-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanco', '0011_alter_contracts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='company_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contracts',
            name='freelancer_started',
            field=models.BooleanField(default=False),
        ),
    ]
