# Generated by Django 4.0.6 on 2022-08-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelanco', '0012_contracts_company_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='eth_deposited',
            field=models.BooleanField(default=False),
        ),
    ]
